#!/bin/sh

out() { printf '\033[1;34m-> \033[m%s\n' "$@" >&2 ;}
error() { printf '\033[1;31m!> \033[m%s\n' "$@" >&2 ;}
die() { printf '\033[1;31m!> \033[m%s\n' "$@" >&2 ; exit 1 ;}

cache_dir="$KISS_ROOT${XDG_CACHE_HOME:-$HOME/.cache}/fat"

usage() {
    out "fat [g|i|s|u|v] [pkg] [pkg] [pkg]" \
        "get:         Install package from the given url" \
        "install:     Install a package" \
        "search:      Search for a package" \
        "update:      Update manifests" \
        "version:     Package installer version"
    exit 0
}

fn_update() {
    [ "$FAT_PATH" ] || die "Please add \$FAT_PATH to your environment before updating"
    out "Getting the latest manifest"
    mkdir -p "$cache_dir/manifest"
    rm -f "$cache_dir/manifest/"*
    :> "$cache_dir/manifest/list"
    for dist in $(echo "$FAT_PATH" | tr ';' ' ') ; do
        manloc="$cache_dir/manifest/$(echo "$dist" | sed -E 's/https?:\/\///g;s/\/.*//g')"
        curl "$dist/manifest" -Lo "$manloc"
        printf '%s\t%s\n' "$dist" "$manloc" >> "$cache_dir/manifest/list"
    done
}

fn_checkmanifest() {
    [ -e "$cache_dir/manifest/list" ] ||
        die "Manifest list could not be found, please run" "fat update"
    while IFS="$(printf '\t')" read -r dist manloc ; do
        grep -q "^$1\t" "$manloc" || continue
        pkginfo="$(grep "^$1\t" "$manloc" | sort -V | sed '$!d')"
        export dist pkginfo
        break
    done < "$cache_dir/manifest/list"
}

fn_get() {
    prog=1
    for src in "$@" ; do
        mkdir -p "$cache_dir/fat_get"
        out "Installing ${src##*/} ($prog/$#)"
        out "Downloading from $src"
        curl "$src" -Lo "$cache_dir/manual/${src##*/}" || die "Failed to download package from $src"
        out "Installing ${src##*/} through kiss"
        kiss i "$cache_dir/fat_get/${src##*/}" || die "Failed to install ${src##*/}"
        prog=$(( prog + 1 ))
    done
}

fn_search() {
    [ -e "$cache_dir/manifest/list" ] ||
        die "Manifest list could not be found, please run" "fat update"
    while IFS="$(printf '\t')" read -r dist manloc ; do
        out "$dist:"
        grep "^$1\t" "$manloc" | sort -V | sed '$!d' | cut -f 1,2
    done < "$cache_dir/manifest/list"
}

fn_install() {
    prog=1
    for pkg in "$@" ; do
        out "Starting installation for $pkg ($prog/$#)"
        out "Getting package location"
        fn_checkmanifest "$pkg" || die "$pkg could not be found on any repository"

        out "Checking package dependencies"
        pkgdeps="$(echo "$pkginfo" | cut -f 5)"

        for dep in $pkgdeps; do
            # Skip dependencies if they are already installed.
            # Can be skipped if FAT_FORCE variable exists.
            [ "$FAT_FORCE" ] ||
                { kiss l "$dep" >/dev/null 2>&1 && continue ;}
            fn_install "$dep"
        done

        fn_checkmanifest "$pkg" 
        out "Downloading the package"
        pkgdest="$(echo "$pkginfo" | cut -f 3)"

        # If the source is https?, change the # to %23
        case "$dist" in
            http*://*) pkgloc="$dist/$(echo "$pkginfo" | cut -f 3 | sed 's/#/%23/g' )" ;;
            *) pkgloc="$dist/$(echo "$pkginfo" | cut -f 3 )" ;;
        esac

        mkdir -p "$cache_dir/bin"

        curl "$pkgloc" -fLo "$cache_dir/bin/$pkgdest" ||
            die "Could not download the tarball"

        out "Checking sha256sums"
        [ "$(echo "$pkginfo" | cut -f 4)" = "$(sha256sum "$cache_dir/bin/$pkgdest" | awk '{print $1}')" ] || die "Checksums mismatch"

        out "Checking gpg signature"
        mkdir -p "$cache_dir/sig"
        curl "${pkgloc}.asc" -fLo "$cache_dir/sig/${pkgdest}.asc" || die "Could not download signature"
        gpg --verify "$cache_dir/sig/${pkgdest}.asc" "$cache_dir/bin/$pkgdest"

        out "Installing package with kiss"
        kiss i "$cache_dir/bin/$pkgdest"
        
    done
}


main() {
    [ "$1" ] || usage
    prog="$1" ; shift
    case "$prog" in
        g|get) fn_get "$@" ;;
        i|install) fn_install "$@" ;;
        s|search) fn_search "$1" ;;
        u|update) fn_update "$@" ;;
        v|version) out "fat-0.1.0" ;;
        -h|--help|help|h) usage ;;
        *) die "$prog is not a valid command" ;;
    esac
}

main "$@"
